clear;
close all;
th = 0:pi/8:2*pi - pi/8;
inphase = 2 * cos(th) - 2.5;
quadr = 2 * sin(th) + 2.5;
inphase = [inphase; -inphase; inphase; -inphase]; 
inphase = inphase(:);
quadr = [quadr; -quadr; -quadr; quadr];
quadr = quadr(:);
const = inphase + 1i*quadr;
A = sum((abs(const)).^2)/length(const);
a = abs((-2.5 + 4.5i) - (-1.73463 + 4.34776i))/2;
scatterplot(const,1,0,'b*');
grid on;
%set(gcf,'color','w');
%ax = gca;
%ax.Color = 'w';
%ax.XColor = 'k';
%ax.YColor = 'k';
%ax.GridAlpha = 0.7;
%ax.GridColor = 'k';
%ax.GridLineStyle = '--';